name: CI

on:
    push:

jobs:
    turbo-chart:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout
              uses: actions/checkout@v5
              with:
                  fetch-depth: 0 # Needed for git history

            - name: Install Node.js
              uses: actions/setup-node@v5
              with:
                  node-version: 22
                  cache: "pnpm"

            - name: Install dependencies
              run: |
                  corepack enable
                  pnpm install

            - name: Check
              run: |
                  node --run check

            - name: Build
              run: |
                  node --run build

            - name: Create release
              if: github.ref == 'refs/heads/main'
              run: |
                  node --experimental-strip-types scripts/release.mts
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GITHUB_REPOSITORY: ${{ github.repository }}
